// Code generated by "stringer -type Permission"; DO NOT EDIT.

package disgord

import "strconv"

const _Permission_name = "PermissionCreateInstantInvitePermissionKickMembersPermissionBanMembersPermissionAdministratorPermissionManageChannelsPermissionManageGuildPermissionAddReactionsPermissionViewAuditLogPermissionPrioritySpeakerPermissionViewChannelPermissionSendMessagesPermissionSendTTSMessagesPermissionManageMessagesPermissionEmbedLinksPermissionAttachFilesPermissionReadMessageHistoryPermissionMentionEveryonePermissionAllTextPermissionUseExternalEmojisPermissionConnectPermissionSpeakPermissionMuteMembersPermissionDeafenMembersPermissionMoveMembersPermissionUseVADPermissionChangeNicknamePermissionManageNicknamesPermissionManageRolesPermissionManageWebhooksPermissionManageEmojis"

var _Permission_map = map[Permission]string{
	1:          _Permission_name[0:29],
	2:          _Permission_name[29:50],
	4:          _Permission_name[50:70],
	8:          _Permission_name[70:93],
	16:         _Permission_name[93:117],
	32:         _Permission_name[117:138],
	64:         _Permission_name[138:160],
	128:        _Permission_name[160:182],
	256:        _Permission_name[182:207],
	1024:       _Permission_name[207:228],
	2048:       _Permission_name[228:250],
	4096:       _Permission_name[250:275],
	8192:       _Permission_name[275:299],
	16384:      _Permission_name[299:319],
	32768:      _Permission_name[319:340],
	65536:      _Permission_name[340:368],
	131072:     _Permission_name[368:393],
	261120:     _Permission_name[393:410],
	262144:     _Permission_name[410:437],
	1048576:    _Permission_name[437:454],
	2097152:    _Permission_name[454:469],
	4194304:    _Permission_name[469:490],
	8388608:    _Permission_name[490:513],
	16777216:   _Permission_name[513:534],
	33554432:   _Permission_name[534:550],
	67108864:   _Permission_name[550:574],
	134217728:  _Permission_name[574:599],
	268435456:  _Permission_name[599:620],
	536870912:  _Permission_name[620:644],
	1073741824: _Permission_name[644:666],
}

func (i Permission) String() string {
	if str, ok := _Permission_map[i]; ok {
		return str
	}
	return "Permission(" + strconv.FormatInt(int64(i), 10) + ")"
}
