// Code generated by generate/interfaces; DO NOT EDIT.

package disgord

import (
	"context"
	"github.com/andersfylling/disgord/internal/gateway"
	"net/url"
)

type channelQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ ChannelQueryBuilder = &channelQueryBuilderNop{}

func (c *channelQueryBuilderNop) WithContext(ctx context.Context) ChannelQueryBuilder {
	c.Ctx = ctx
	return &c
}

func (c *channelQueryBuilderNop) WithFlags(flags ...Flag) ChannelQueryBuilder {
	c.Flags = mergeFlags(flags)
	return &c
}

func (c *channelQueryBuilderNop) AddDMParticipant() error {
	return nil
}

func (c *channelQueryBuilderNop) CreateInvite() CreateChannelInviteBuilder {
	return nil
}

func (c *channelQueryBuilderNop) CreateMessage() (*Message, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) CreateWebhook() (*Webhook, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) Delete() (*Channel, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) DeleteMessages() error {
	return nil
}

func (c *channelQueryBuilderNop) DeletePermission() error {
	return nil
}

func (c *channelQueryBuilderNop) Get() (*Channel, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) GetInvites() ([]*Invite, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) GetMessages() ([]*Message, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) GetPinnedMessages() ([]*Message, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) GetWebhooks() ([]*Webhook, error) {
	return nil, nil
}

func (c *channelQueryBuilderNop) KickParticipant() error {
	return nil
}

func (c *channelQueryBuilderNop) Message() MessageQueryBuilder {
	return nil
}

func (c *channelQueryBuilderNop) TriggerTypingIndicator() error {
	return nil
}

func (c *channelQueryBuilderNop) UpdateBuilder() UpdateChannelBuilder {
	return nil
}

func (c *channelQueryBuilderNop) UpdatePermissions() error {
	return nil
}

type clientQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ ClientQueryBuilder = &clientQueryBuilderNop{}

func (c *clientQueryBuilderNop) WithContext(ctx context.Context) ClientQueryBuilderExecutables {
	c.Ctx = ctx
	return &c
}

func (c *clientQueryBuilderNop) WithFlags(flags ...Flag) ClientQueryBuilderExecutables {
	c.Flags = mergeFlags(flags)
	return &c
}

func (c *clientQueryBuilderNop) BotAuthorizeURL() (*url.URL, error) {
	return nil, nil
}

func (c *clientQueryBuilderNop) Channel() ChannelQueryBuilder {
	return nil
}

func (c *clientQueryBuilderNop) CreateGuild() (*Guild, error) {
	return nil, nil
}

func (c *clientQueryBuilderNop) CurrentUser() CurrentUserQueryBuilder {
	return nil
}

func (c *clientQueryBuilderNop) Gateway() GatewayQueryBuilder {
	return nil
}

func (c *clientQueryBuilderNop) GetVoiceRegions() ([]*VoiceRegion, error) {
	return nil, nil
}

func (c *clientQueryBuilderNop) Guild() GuildQueryBuilder {
	return nil
}

func (c *clientQueryBuilderNop) Invite() InviteQueryBuilder {
	return nil
}

func (c *clientQueryBuilderNop) SendMsg() (*Message, error) {
	return nil, nil
}

func (c *clientQueryBuilderNop) User() UserQueryBuilder {
	return nil
}

type currentUserQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ CurrentUserQueryBuilder = &currentUserQueryBuilderNop{}

func (c *currentUserQueryBuilderNop) WithContext(ctx context.Context) CurrentUserQueryBuilder {
	c.Ctx = ctx
	return &c
}

func (c *currentUserQueryBuilderNop) WithFlags(flags ...Flag) CurrentUserQueryBuilder {
	c.Flags = mergeFlags(flags)
	return &c
}

func (c *currentUserQueryBuilderNop) CreateGroupDM() (*Channel, error) {
	return nil, nil
}

func (c *currentUserQueryBuilderNop) Get() (*User, error) {
	return nil, nil
}

func (c *currentUserQueryBuilderNop) GetGuilds() ([]*Guild, error) {
	return nil, nil
}

func (c *currentUserQueryBuilderNop) GetUserConnections() ([]*UserConnection, error) {
	return nil, nil
}

func (c *currentUserQueryBuilderNop) LeaveGuild() error {
	return nil
}

func (c *currentUserQueryBuilderNop) UpdateBuilder() UpdateCurrentUserBuilder {
	return nil
}

type gatewayQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ GatewayQueryBuilder = &gatewayQueryBuilderNop{}

func (g *gatewayQueryBuilderNop) WithContext(ctx context.Context) GatewayQueryBuilder {
	g.Ctx = ctx
	return &g
}

func (g *gatewayQueryBuilderNop) BotGuildsReady() {
	return
}

func (g *gatewayQueryBuilderNop) BotReady() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelCreate() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelCreateChan() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelDelete() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelDeleteChan() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelPinsUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelPinsUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) ChannelUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) Connect() error {
	return nil
}

func (g *gatewayQueryBuilderNop) Disconnect() error {
	return nil
}

func (g *gatewayQueryBuilderNop) DisconnectOnInterrupt() error {
	return nil
}

func (g *gatewayQueryBuilderNop) Dispatch() (Snowflake, error) {
	return 0, nil
}

func (g *gatewayQueryBuilderNop) Get() (*gateway.Gateway, error) {
	return nil, nil
}

func (g *gatewayQueryBuilderNop) GetBot() (*gateway.GatewayBot, error) {
	return nil, nil
}

func (g *gatewayQueryBuilderNop) GuildBanAdd() {
	return
}

func (g *gatewayQueryBuilderNop) GuildBanAddChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildBanRemove() {
	return
}

func (g *gatewayQueryBuilderNop) GuildBanRemoveChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildCreate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildCreateChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildDelete() {
	return
}

func (g *gatewayQueryBuilderNop) GuildDeleteChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildEmojisUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildEmojisUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildIntegrationsUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildIntegrationsUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMemberAdd() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMemberAddChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMemberRemove() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMemberRemoveChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMembersChunk() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMembersChunkChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMemberUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildMemberUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildRoleCreate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildRoleCreateChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildRoleDelete() {
	return
}

func (g *gatewayQueryBuilderNop) GuildRoleDeleteChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildRoleUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildRoleUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) GuildUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) GuildUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) InteractionCreate() {
	return
}

func (g *gatewayQueryBuilderNop) InteractionCreateChan() {
	return
}

func (g *gatewayQueryBuilderNop) InviteCreate() {
	return
}

func (g *gatewayQueryBuilderNop) InviteCreateChan() {
	return
}

func (g *gatewayQueryBuilderNop) InviteDelete() {
	return
}

func (g *gatewayQueryBuilderNop) InviteDeleteChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageCreate() {
	return
}

func (g *gatewayQueryBuilderNop) MessageCreateChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageDelete() {
	return
}

func (g *gatewayQueryBuilderNop) MessageDeleteBulk() {
	return
}

func (g *gatewayQueryBuilderNop) MessageDeleteBulkChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageDeleteChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionAdd() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionAddChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionRemove() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionRemoveAll() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionRemoveAllChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionRemoveChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionRemoveEmoji() {
	return
}

func (g *gatewayQueryBuilderNop) MessageReactionRemoveEmojiChan() {
	return
}

func (g *gatewayQueryBuilderNop) MessageUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) MessageUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) PresenceUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) PresenceUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) Ready() {
	return
}

func (g *gatewayQueryBuilderNop) ReadyChan() {
	return
}

func (g *gatewayQueryBuilderNop) Resumed() {
	return
}

func (g *gatewayQueryBuilderNop) ResumedChan() {
	return
}

func (g *gatewayQueryBuilderNop) StayConnectedUntilInterrupted() error {
	return nil
}

func (g *gatewayQueryBuilderNop) TypingStart() {
	return
}

func (g *gatewayQueryBuilderNop) TypingStartChan() {
	return
}

func (g *gatewayQueryBuilderNop) UserUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) UserUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) VoiceServerUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) VoiceServerUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) VoiceStateUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) VoiceStateUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) WebhooksUpdate() {
	return
}

func (g *gatewayQueryBuilderNop) WebhooksUpdateChan() {
	return
}

func (g *gatewayQueryBuilderNop) WithCtrl() SocketHandlerRegistrator {
	return nil
}

func (g *gatewayQueryBuilderNop) WithMiddleware() SocketHandlerRegistrator {
	return nil
}

type guildEmojiQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ GuildEmojiQueryBuilder = &guildEmojiQueryBuilderNop{}

func (g *guildEmojiQueryBuilderNop) WithContext(ctx context.Context) GuildEmojiQueryBuilder {
	g.Ctx = ctx
	return &g
}

func (g *guildEmojiQueryBuilderNop) WithFlags(flags ...Flag) GuildEmojiQueryBuilder {
	g.Flags = mergeFlags(flags)
	return &g
}

func (g *guildEmojiQueryBuilderNop) Delete() error {
	return nil
}

func (g *guildEmojiQueryBuilderNop) Get() (*Emoji, error) {
	return nil, nil
}

func (g *guildEmojiQueryBuilderNop) UpdateBuilder() UpdateGuildEmojiBuilder {
	return nil
}

type guildMemberQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ GuildMemberQueryBuilder = &guildMemberQueryBuilderNop{}

func (g *guildMemberQueryBuilderNop) WithContext(ctx context.Context) GuildMemberQueryBuilder {
	g.Ctx = ctx
	return &g
}

func (g *guildMemberQueryBuilderNop) WithFlags(flags ...Flag) GuildMemberQueryBuilder {
	g.Flags = mergeFlags(flags)
	return &g
}

func (g *guildMemberQueryBuilderNop) AddRole() error {
	return nil
}

func (g *guildMemberQueryBuilderNop) Ban() error {
	return nil
}

func (g *guildMemberQueryBuilderNop) Get() (*Member, error) {
	return nil, nil
}

func (g *guildMemberQueryBuilderNop) GetPermissions() (PermissionBit, error) {
	return 0, nil
}

func (g *guildMemberQueryBuilderNop) Kick() error {
	return nil
}

func (g *guildMemberQueryBuilderNop) RemoveRole() error {
	return nil
}

func (g *guildMemberQueryBuilderNop) UpdateBuilder() UpdateGuildMemberBuilder {
	return nil
}

type guildQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ GuildQueryBuilder = &guildQueryBuilderNop{}

func (g *guildQueryBuilderNop) WithContext(ctx context.Context) GuildQueryBuilder {
	g.Ctx = ctx
	return &g
}

func (g *guildQueryBuilderNop) WithFlags(flags ...Flag) GuildQueryBuilder {
	g.Flags = mergeFlags(flags)
	return &g
}

func (g *guildQueryBuilderNop) CreateChannel() (*Channel, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) CreateEmoji() (*Emoji, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) CreateIntegration() error {
	return nil
}

func (g *guildQueryBuilderNop) CreateMember() (*Member, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) CreateRole() (*Role, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) Delete() error {
	return nil
}

func (g *guildQueryBuilderNop) DeleteIntegration() error {
	return nil
}

func (g *guildQueryBuilderNop) Emoji() GuildEmojiQueryBuilder {
	return nil
}

func (g *guildQueryBuilderNop) EstimatePruneMembersCount() (int, error) {
	return 0, nil
}

func (g *guildQueryBuilderNop) Get() (*Guild, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetAuditLogs() GuildAuditLogsBuilder {
	return nil
}

func (g *guildQueryBuilderNop) GetBan() (*Ban, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetBans() ([]*Ban, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetChannels() ([]*Channel, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetEmbed() (*GuildEmbed, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetEmojis() ([]*Emoji, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetIntegrations() ([]*Integration, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetInvites() ([]*Invite, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetMembers() ([]*Member, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetRoles() ([]*Role, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetVanityURL() (*Invite, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetVoiceRegions() ([]*VoiceRegion, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) GetWebhooks() ([]*Webhook, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) KickVoiceParticipant() error {
	return nil
}

func (g *guildQueryBuilderNop) Member() GuildMemberQueryBuilder {
	return nil
}

func (g *guildQueryBuilderNop) PruneMembers() error {
	return nil
}

func (g *guildQueryBuilderNop) Role() GuildRoleQueryBuilder {
	return nil
}

func (g *guildQueryBuilderNop) SetCurrentUserNick() (string, error) {
	return "", nil
}

func (g *guildQueryBuilderNop) SyncIntegration() error {
	return nil
}

func (g *guildQueryBuilderNop) UnbanUser() error {
	return nil
}

func (g *guildQueryBuilderNop) UpdateBuilder() UpdateGuildBuilder {
	return nil
}

func (g *guildQueryBuilderNop) UpdateChannelPositions() error {
	return nil
}

func (g *guildQueryBuilderNop) UpdateEmbedBuilder() UpdateGuildEmbedBuilder {
	return nil
}

func (g *guildQueryBuilderNop) UpdateIntegration() error {
	return nil
}

func (g *guildQueryBuilderNop) UpdateRolePositions() ([]*Role, error) {
	return nil, nil
}

func (g *guildQueryBuilderNop) VoiceChannel() VoiceChannelQueryBuilder {
	return nil
}

type guildRoleQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ GuildRoleQueryBuilder = &guildRoleQueryBuilderNop{}

func (g *guildRoleQueryBuilderNop) WithContext(ctx context.Context) GuildRoleQueryBuilder {
	g.Ctx = ctx
	return &g
}

func (g *guildRoleQueryBuilderNop) WithFlags(flags ...Flag) GuildRoleQueryBuilder {
	g.Flags = mergeFlags(flags)
	return &g
}

func (g *guildRoleQueryBuilderNop) Delete() error {
	return nil
}

func (g *guildRoleQueryBuilderNop) UpdateBuilder() UpdateGuildRoleBuilder {
	return nil
}

type inviteQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ InviteQueryBuilder = &inviteQueryBuilderNop{}

func (i *inviteQueryBuilderNop) WithContext(ctx context.Context) InviteQueryBuilder {
	i.Ctx = ctx
	return &i
}

func (i *inviteQueryBuilderNop) WithFlags(flags ...Flag) InviteQueryBuilder {
	i.Flags = mergeFlags(flags)
	return &i
}

func (i *inviteQueryBuilderNop) Delete() (*Invite, error) {
	return nil, nil
}

func (i *inviteQueryBuilderNop) Get() (*Invite, error) {
	return nil, nil
}

type messageQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ MessageQueryBuilder = &messageQueryBuilderNop{}

func (m *messageQueryBuilderNop) WithContext(ctx context.Context) MessageQueryBuilder {
	m.Ctx = ctx
	return &m
}

func (m *messageQueryBuilderNop) WithFlags(flags ...Flag) MessageQueryBuilder {
	m.Flags = mergeFlags(flags)
	return &m
}

func (m *messageQueryBuilderNop) CrossPost() (*Message, error) {
	return nil, nil
}

func (m *messageQueryBuilderNop) Delete() error {
	return nil
}

func (m *messageQueryBuilderNop) DeleteAllReactions() error {
	return nil
}

func (m *messageQueryBuilderNop) Get() (*Message, error) {
	return nil, nil
}

func (m *messageQueryBuilderNop) Pin() error {
	return nil
}

func (m *messageQueryBuilderNop) Reaction() ReactionQueryBuilder {
	return nil
}

func (m *messageQueryBuilderNop) SetContent() (*Message, error) {
	return nil, nil
}

func (m *messageQueryBuilderNop) SetEmbed() (*Message, error) {
	return nil, nil
}

func (m *messageQueryBuilderNop) Unpin() error {
	return nil
}

func (m *messageQueryBuilderNop) UpdateBuilder() UpdateMessageBuilder {
	return nil
}

type reactionQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ ReactionQueryBuilder = &reactionQueryBuilderNop{}

func (r *reactionQueryBuilderNop) WithContext(ctx context.Context) ReactionQueryBuilder {
	r.Ctx = ctx
	return &r
}

func (r *reactionQueryBuilderNop) WithFlags(flags ...Flag) ReactionQueryBuilder {
	r.Flags = mergeFlags(flags)
	return &r
}

func (r *reactionQueryBuilderNop) Create() error {
	return nil
}

func (r *reactionQueryBuilderNop) DeleteOwn() error {
	return nil
}

func (r *reactionQueryBuilderNop) DeleteUser() error {
	return nil
}

func (r *reactionQueryBuilderNop) Get() ([]*User, error) {
	return nil, nil
}

type userQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ UserQueryBuilder = &userQueryBuilderNop{}

func (u *userQueryBuilderNop) WithContext(ctx context.Context) UserQueryBuilder {
	u.Ctx = ctx
	return &u
}

func (u *userQueryBuilderNop) WithFlags(flags ...Flag) UserQueryBuilder {
	u.Flags = mergeFlags(flags)
	return &u
}

func (u *userQueryBuilderNop) CreateDM() (*Channel, error) {
	return nil, nil
}

func (u *userQueryBuilderNop) Get() (*User, error) {
	return nil, nil
}

type voiceChannelQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ VoiceChannelQueryBuilder = &voiceChannelQueryBuilderNop{}

func (v *voiceChannelQueryBuilderNop) WithContext(ctx context.Context) ChannelQueryBuilder {
	v.Ctx = ctx
	return &v
}

func (v *voiceChannelQueryBuilderNop) WithFlags(flags ...Flag) ChannelQueryBuilder {
	v.Flags = mergeFlags(flags)
	return &v
}

func (v *voiceChannelQueryBuilderNop) Connect() (VoiceConnection, error) {
	return nil, nil
}

func (v *voiceChannelQueryBuilderNop) CreateInvite() CreateChannelInviteBuilder {
	return nil
}

func (v *voiceChannelQueryBuilderNop) Delete() (*Channel, error) {
	return nil, nil
}

func (v *voiceChannelQueryBuilderNop) DeletePermission() error {
	return nil
}

func (v *voiceChannelQueryBuilderNop) Get() (*Channel, error) {
	return nil, nil
}

func (v *voiceChannelQueryBuilderNop) GetInvites() ([]*Invite, error) {
	return nil, nil
}

func (v *voiceChannelQueryBuilderNop) JoinManual() (*VoiceStateUpdate, *VoiceServerUpdate, error) {
	return nil, nil, nil
}

func (v *voiceChannelQueryBuilderNop) UpdateBuilder() UpdateChannelBuilder {
	return nil
}

func (v *voiceChannelQueryBuilderNop) UpdatePermissions() error {
	return nil
}

type webhookQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ WebhookQueryBuilder = &webhookQueryBuilderNop{}

func (w *webhookQueryBuilderNop) WithContext(ctx context.Context) WebhookQueryBuilder {
	w.Ctx = ctx
	return &w
}

func (w *webhookQueryBuilderNop) WithFlags(flags ...Flag) WebhookQueryBuilder {
	w.Flags = mergeFlags(flags)
	return &w
}

func (w *webhookQueryBuilderNop) Delete() error {
	return nil
}

func (w *webhookQueryBuilderNop) Execute() (*Message, error) {
	return nil, nil
}

func (w *webhookQueryBuilderNop) ExecuteGitHubWebhook() (*Message, error) {
	return nil, nil
}

func (w *webhookQueryBuilderNop) ExecuteSlackWebhook() (*Message, error) {
	return nil, nil
}

func (w *webhookQueryBuilderNop) Get() (*Webhook, error) {
	return nil, nil
}

func (w *webhookQueryBuilderNop) UpdateBuilder() UpdateWebhookBuilder {
	return nil
}

func (w *webhookQueryBuilderNop) WithToken() WebhookWithTokenQueryBuilder {
	return nil
}

type webhookWithTokenQueryBuilderNop struct {
	Ctx       context.Context
	Flags     Flag
	ChannelID Snowflake
	GuildID   Snowflake
	UserID    Snowflake
}

var _ WebhookWithTokenQueryBuilder = &webhookWithTokenQueryBuilderNop{}

func (w *webhookWithTokenQueryBuilderNop) WithContext(ctx context.Context) WebhookWithTokenQueryBuilder {
	w.Ctx = ctx
	return &w
}

func (w *webhookWithTokenQueryBuilderNop) WithFlags(flags ...Flag) WebhookWithTokenQueryBuilder {
	w.Flags = mergeFlags(flags)
	return &w
}

func (w *webhookWithTokenQueryBuilderNop) Delete() error {
	return nil
}

func (w *webhookWithTokenQueryBuilderNop) Execute() (*Message, error) {
	return nil, nil
}

func (w *webhookWithTokenQueryBuilderNop) Get() (*Webhook, error) {
	return nil, nil
}

func (w *webhookWithTokenQueryBuilderNop) UpdateBuilder() UpdateWebhookBuilder {
	return nil
}
