package disgord

// Warning: This file has been automatically generated by generate/events/main.go
// Do NOT make changes here, instead adapt events.go and event/events.go and run go generate

import (
	"context"

	"github.com/andersfylling/disgord/event"
)

// these "simple" handler can be used, if you don't care about the actual event data
type SimplestHandler = func()
type SimpleHandler = func(session Session)

// ---------------------------

{{range .}}
{{if .IsDiscordEvent}}
{{.RenderDocs}}
const Event{{.}} = event.{{.}} {{end}}

func (h *{{.}}) registerContext(ctx context.Context) { h.Ctx = ctx }

// {{.}}Handler is triggered in {{.}} events
type {{.}}Handler = func(session Session, h *{{.}})

// --------------------------- {{end}}