// Package endpoint holds all discord urls for the REST endpoints
package endpoint

// endpoints/paths
const (
	discordAPI   = "https://discord.com/api"
	auditlogs    = "/audit-logs"
	channels     = "/channels"
	messages     = "/messages"
	bulkDelete   = "/bulk-delete"
	recipients   = "/recipients"
	pins         = "/pins"
	typing       = "/typing"
	permissions  = "/permissions"
	invites      = "/invites"
	reactions    = "/reactions"
	me           = "/@me"
	emojis       = "/emojis"
	guilds       = "/guilds"
	users        = "/users"
	connections  = "/connections"
	voice        = "/voice"
	regions      = "/regions"
	webhooks     = "/webhooks"
	slack        = "/slack"
	github       = "/github"
	members      = "/members"
	nick         = "/nick"
	roles        = "/roles"
	bans         = "/bans"
	prune        = "/prune"
	integrations = "/integrations"
	sync         = "/sync"
	embed        = "/embed"
	vanityURL    = "/vanity-url"
	gateway      = "/gateway"
	version      = "/v"
)
