name: Unit tests
on: [pull_request]
jobs:
  versions-old:
    name: go version
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        go: ['1.15', '1.16']
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get dependencies
        run: go mod download
      - name: test
        run: go test -covermode=atomic -v -race -short ./...

  versions:
    name: go version
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        go: [ '1.17' ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get dependencies
        run: go mod download
      - name: test
        run: go test -shuffle=on -covermode=atomic -v -race -short ./...
